# Create a workflow tha triggers manually and: 
# 1. Print our slogan
# 2. Guess our magic number

name: SloganANDMagicNumber

on: workflow_dispatch

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Write Slogan
      run: echo "${{vars.SLOGAN}}"
    - name: Magic Number
      run: echo "${{secrets.MY_MAGIC_NUMBER}}"
