name: test-matrix-enviroments
on: workflow_dispatch
jobs: 
  print-my-variabels:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        environment: [Test, Development, Production]
    environment: ${{ matrix.environment }}
    steps:
      - name: Print environment message
        run: |
          echo "${{ vars.MIN_VARIABEL }}"

          HACKED_API_NYCKEL="${secrets.MIN_API_NYCKEL//a/X}"
          echo "HACKED_API_NYCKEL"
